[window]
    padding.x = 10
    padding.y = 10
    decorations = "none"
    decorations_theme_variant = "Dark"

[font]
    normal.family = "Fira Code Retina"
    size = 10
    offset.x = 0
    offset.y = 1

[scrolling]
    history = 10000
    multiplier = 5

[cursor]
    style.shape = "Beam"
    style.blinking = "On"

[mouse]
    hide_when_typing = true

[colors.primary]
    foreground = "#a9a9a9"
    background = "#282c34"