#!/bin/bash
# uses: rofi i3wm

# read theming from rasi file
# only necessary when using icons instead of text
foreground=$(grep 'foreground-color:' "$HOME/.config/rofi/themes/icons.rasi" | awk '{sub(/;/, "", $2); print $2}')
font_glyph=$(grep 'glyphs:' "$HOME/.config/rofi/themes/icons.rasi" | sed 's/.*"\([^"]*\)".*/\1/')

# define available actions
cycle="cycle\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"
split="split\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"
stacking="stacking\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"
tabbed="tabbed\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"

# main function
rofi_main() {
    options_string="$cycle\n$split\n$stacking\n$tabbed"
    selection=$(echo -e "$options_string" | rofi -dmenu -theme "icons" \
        -theme-str 'listview {columns: 1; lines: 5;}')

    case $selection in
        "cycle")
            i3-msg layout toggle
            rofi_main
            ;;
        "split")
            i3-msg layout toggle split
            ;;
        "stacking")
            i3-msg layout stacking
            ;;
        "tabbed")
            i3-msg layout tabbed
            ;;
        *)
            exit 0
            ;;
    esac
}

# main entry point to script
rofi_main