#!/bin/bash

# read foreground-color from rofi theme
fg_color=$(grep 'foreground-color:' "$HOME/.config/rofi/themes/icon-bar.rasi" | awk '{sub(/;/, "", $2); print $2}')
glyphs="Font Awesome 6 Free Regular"

# define available options
cycle="cycle\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
split="split\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
stacking="stacking\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
tabbed="tabbed\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"

# main function
rofi_main() {
    options_string="$cycle\n$split\n$stacking\n$tabbed"
    choice=$(echo -e "$options_string" | rofi -dmenu -theme "icon-bar" \
        -theme-str 'listview {columns: 1; lines: 4;}')

    case 1 in
        $(echo "$choice" | grep -q "cycle" && echo 1) )
            i3-msg layout toggle
            rofi_main
            ;;
        $(echo "$choice" | grep -q "split" && echo 1) )
            i3-msg layout toggle split
            ;;
        $(echo "$choice" | grep -q "stacking" && echo 1) )
            i3-msg layout stacking
            ;;
        $(echo "$choice" | grep -q "tabbed" && echo 1) )
            i3-msg layout tabbed
            ;;
        *)
            exit 0
            ;;
    esac
}

# main entry point to script
rofi_main