#!/bin/bash

# read foreground-color from rofi theme
fg_color=$(grep 'foreground-color:' "$HOME/.config/rofi/themes/icons.rasi" | awk '{sub(/;/, "", $2); print $2}')
glyphs="Font Awesome 6 Free Regular"

# define available options
lock="lock\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
suspend="suspend\0icon\x1f<span font='$glyphs' color='$fg_color'>󰤄</span>"
reboot="reboot\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
i3_reload="i3 reload\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
i3_restart="i3 restart\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"
poweroff="poweroff\0icon\x1f<span font='$glyphs' color='$fg_color'></span>"

# function to confirm user action
rofi_confirm(){
    echo -e "ok\0icon\x1f<span font='$glyphs' color='$fg_color'></span>\ncancel\0icon\x1f<span font='$glyphs' color='$fg_color'></span>" |
    rofi -dmenu -mesg "$selected?" -theme "icons" \
        -theme-str 'listview {columns: 1; lines: 2;}' \
        -theme-str 'textbox-current-entry {enabled: false;}';
}

# main function
rofi_main() {
    options="$lock\n$suspend\n$reboot\n$i3_reload\n$i3_restart\n$poweroff"
    selected=$(echo -e "$options" | rofi -dmenu -theme "icons" \
        -theme-str 'listview {columns: 1; lines: 6;}')

    case "$selected" in
        "lock")
            i3lock -efti ~/pictures/wallpapers/lockscreen.png
            ;;
        "suspend")
            if [ "$(rofi_confirm)" == "ok" ]; then
                i3lock -efti ~/pictures/wallpapers/lockscreen.png && systemctl suspend
            else
                return
            fi
            ;;        
        "reboot")
            if [ "$(rofi_confirm)" == "ok" ]; then
                systemctl reboot
            else
                return
            fi
            ;;
        "i3 reload")
            i3-msg reload
            ;;
        "i3 restart")
            i3-msg restart
            ;;        
        "poweroff")
            if [ "$(rofi_confirm)" == "ok" ]; then
                systemctl poweroff
            else
                return
            fi
            ;;        
        *)
            exit 0
            ;;
        esac
}

# main entry point to script
rofi_main