#!/bin/bash
# uses: rofi scrot xclip dunst

# read theming from rasi file
# only necessary when using icons instead of text
foreground=$(grep 'foreground-color:' "$HOME/.config/rofi/themes/icons.rasi" | awk '{sub(/;/, "", $2); print $2}')
font_glyph=$(grep 'glyphs:' "$HOME/.config/rofi/themes/icons.rasi" | sed 's/.*"\([^"]*\)".*/\1/')

# define the directory and filename for saved images
screenshot_timestamp=$(date +"%Y%m%d-%H%M%S")
screenshot_directory=~/pictures/screenshots
screenshot_save_path=$screenshot_directory/screenshot_${screenshot_timestamp}.png

# define how many seconds to wait before taking screenshot in `wait` option
wait_secs=3

# define available actions
copy="copy\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"
save="save\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"
wait="wait "$wait_secs""s"\0icon\x1f<span font='$font_glyph' color='$foreground'></span>"

# function to select and copy an area of the screen to the clipboard
copy() {
    if scrot -s /tmp/screenshot.png; then
        xclip -selection clipboard -t image/png /tmp/screenshot.png && rm /tmp/screenshot.png
        dunstify -a manage-screenshot "screenshot taken" "selected area copied to clipboard"
    else
        # notif if failed
        exit 0
    fi
}

# function to select and save an area of the screen to $screenshot_directory
save() {
    if scrot -s $screenshot_save_path; then
        xclip -selection clipboard -t image/png $screenshot_save_path
        dunstify -a manage-screenshot "screenshot saved" $screenshot_save_path
    else
        exit 0
    fi
}

# function to wait n seconds and copy the full screen
wait() {
    for (( i = 1; i < $wait_secs ; i++ )); do
        dunstify -a manage-screenshot "capturing full screen" "in $((wait_secs + 1 - i)) seconds..." -r 4502
        sleep 1
    done

    dunstctl close-all
    sleep 1

    if scrot /tmp/screenshot.png; then
        xclip -selection clipboard -t image/png /tmp/screenshot.png && rm /tmp/screenshot.png
        dunstify -a manage-screenshot "screenshot taken" "full screen copied to clipboard" -r 4502
    else
        exit 0
    fi
}

# load rofi with available options
rofi_main() {
    options_string="$copy\n$save\n$wait"
    selected=$(echo -e "$options_string" | rofi -dmenu -theme "icons" \
    -theme-str 'listview {columns: 1; lines: 3;}')

    case $selected in
        "copy")
            copy
            ;;
        "save")
            save
            ;;
        "wait"*)
            wait
            ;;
        *)
            exit 0
            ;;
    esac
}

# main entry point to script
rofi_main