#!/bin/bash

# Function to get the repository name
get_repo_name() {
    repo_path=$(git rev-parse --show-toplevel 2>/dev/null) || echo ""
    repo_name=$(basename "$repo_path")
    echo "$repo_name"
}

# Function to get the current Git branch name
#get_branch_name() {
#    branch=$(git symbolic-ref --short HEAD 2>/dev/null) || echo ""
#    echo "$branch"
#}

# Function to count unstaged files
get_changes() {
    echo -n "$(git status --porcelain | grep -c "^[ MDARCU??]")"
}

# Main script
repo=$(get_repo_name)
#branch=$(get_branch_name)

if [ -n "$repo" ]; then
    changes=$(get_changes)
    echo -e "🔀${repo} \[$(tput setaf 242)\]${changes}\[$(tput sgr0)\] "
fi
