# ~/.bashrc
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
alias backup='python ~/.config/scripts/backup/backup-dotfiles.py'
alias grep='grep --color=auto'
alias gs='git status'
alias gac='git add . && git commit -m'
alias gp='git push -u origin'
alias ls='ls -lA --color=auto --block-size=M'
alias q='python ~/.config/scripts/openai/gpt-chatbot-console.py'
alias rr='ranger'

# api keys
export OPENAI_API_KEY=$(cat ~/documents/auth/openai/openai_api_key.txt)
export PINECONE_API_KEY=$(cat ~/documents/auth/pinecone/pinecone_api_key.txt)

# environment variables
export OPENAI_MODEL='gpt-3.5-turbo'
export PATH=$PATH:~/.local/bin
export PYTHONPATH=$PYTHONPATH:~/.config/scripts/modules
export EDITOR=vim
export VISUAL=vim

# history
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=500
HISTFILESIZE=500
shopt -s histappend

# prompt
PS1='\W -> '
#source /usr/share/git/git-prompt.sh
#export PS1='\w$(__git_ps1 " (%s)") -> \$ '

# powerline
function _update_ps1() {
    PS1=$(powerline-shell $?)
}
if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# terminal
shopt -s checkwinsize

# theme
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK_APPLICATION_PREFER_DARK_THEME=1
export GTK_THEME='Arc-Dark'
export GTK_ICON_THEME="Wings-Dark-Icons"

# XDG paths
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}
export XDG_DATA_DIRS=${XDG_DATA_DIRS:="/usr/local/share:/usr/share"}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:="/etc/xdg"}

# move files to .config
export GNUPGHOME=${XDG_CONFIG_HOME}/gnupg
export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export VIMDOTDIR="$XDG_CONFIG_HOME/vim"
