# ~/.bashrc
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
alias grep='grep --color=auto'
alias gs='git status'
alias gac='git add . && git commit -m'
alias gp='git push -u origin'
alias ls='ls -lA --color=auto --block-size=M'
alias q='~/.config/openai/bin/console-gpt'
alias rr='ranger'

# api keys
export OPENAI_API_KEY=$(cat ~/documents/auth/openai/openai_api_key.txt)
export PINECONE_API_KEY=$(cat ~/documents/auth/pinecone/pinecone_api_key.txt)
export ANTHROPIC_API_KEY=$(cat ~/documents/auth/anthropic/anthropic_api_key.txt)

# environment variables
export PATH=$PATH:$HOME/.local/bin:$HOME/.config/bash/bin/
export EDITOR=vim
export VISUAL=vim

# history
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=500
HISTFILESIZE=500
shopt -s histappend

# basic prompt
PS1='\w -> '

# detailed prompt
function _update_ps1() {
    local is_venv=$(source ps1-is-venv)
    local git_info=$(source ps1-git-info)
    local last_status=$(source ps1-last-exit-code)
    tput smam
    PS1="${is_venv}\[$(tput setaf 214)\]\w \[$(tput sgr0)\]"
    [ -n "${git_info}" ] && PS1+="${git_info}"
    PS1+="${last_status}$\[$(tput sgr0)\] "
}
if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
    PROMPT_COMMAND='_update_ps1;'"$PROMPT_COMMAND"
fi

# terminal
shopt -s checkwinsize

# XDG paths
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}
export XDG_DATA_DIRS=${XDG_DATA_DIRS:="/usr/local/share:/usr/share"}
export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:="/etc/xdg"}

# theme
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK_APPLICATION_PREFER_DARK_THEME=1

# move files to .config
export GNUPGHOME=${XDG_CONFIG_HOME}/gnupg
export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export VIMDOTDIR="$XDG_CONFIG_HOME/vim"
